version: "3.8"

services:
  NAME_SERVICE:
    image: IMAGE
    hostname: NAME_SERVICE.telconet.ec
    domainname: telconet.ec
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:PUERTO_INTERNO_EXP/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - DIR_AMBIENTE/application.properties:/app/application.properties
      - DIR_AMBIENTE/log4j2.xml:/app/log4j2.xml
      - PARAM1:/app/parameters.yml
    networks:
      - microservicio_swarm
    logging:
      driver: none
    deploy:
      replicas: NUM_REPL_SWARM
      update_config:
        parallelism: NUM_REPL_SWARM
        failure_action: rollback
        max_failure_ratio: 0.75
        order: stop-first
      resources:
        limits:
          memory: MEMORIA_LIMITE
        reservations:
          cpus: '0.25'
          memory: 150M
      labels:
        - "com.docker.stack.description=NAME_COMMIT_BRANCH"
        - traefik.enable=true
        - traefik.http.middlewares.MIDDLEWARE_URL.forwardauth.address=FORWARDAUTH_URL
        - traefik.http.middlewares.MIDDLEWARE_URL.forwardauth.trustForwardHeader=true
        - traefik.http.middlewares.MIDDLEWARE_URL.forwardauth.authResponseHeaders=tokenCas
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accesscontrolalloworiginlist=*
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accesscontrolmaxage=86400
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.addvaryheader=true
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accessControlAllowCredentials=true
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accessControlAllowHeaders=*
        - traefik.http.middlewares.MIDDLEWARE_URLHeaders.headers.accessControlExposeHeaders=*
        - traefik.http.services.NAME_SERVICE.loadbalancer.server.port=PUERTO_INTERNO_EXP
        - traefik.http.routers.NAME_SERVICE.rule=URL_TRAEFIK && PathPrefix(`PATH_SERVICE_TRAEFIK`)
        - traefik.http.routers.NAME_SERVICE.middlewares=MIDDLEWARE_URLHeaders, MIDDLEWARE_URL
        - traefik.http.routers.NAME_SERVICE.service=NAME_SERVICE
        - traefik.docker.network=RED_DOCKER_SWARM
        - traefik.http.routers.NAME_SERVICE.entrypoints=web

networks:
  microservicio_swarm:
    external:
      name: RED_DOCKER_SWARM
